// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDnX_34M42xFfE6W8dCdMGM3hortg9Ec-Q',
    appId: '1:930679859953:web:8eabd085ba760b32019750',
    messagingSenderId: '930679859953',
    projectId: 'light-punch-maker-atech1',
    authDomain: 'light-punch-maker-atech1.firebaseapp.com',
    storageBucket: 'light-punch-maker-atech1.firebasestorage.app',
    measurementId: 'G-XPJDVV6JHK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyChRuJhT6oI1wdV1GKbjwf99lbaRYbo8jM',
    appId: '1:930679859953:android:abc7cb1144da1796019750',
    messagingSenderId: '930679859953',
    projectId: 'light-punch-maker-atech1',
    storageBucket: 'light-punch-maker-atech1.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBWuKHgkeYifukK0l2Vsf5rRnCsTJ6BMBI',
    appId: '1:930679859953:ios:51840cc93e9b578b019750',
    messagingSenderId: '930679859953',
    projectId: 'light-punch-maker-atech1',
    storageBucket: 'light-punch-maker-atech1.firebasestorage.app',
    iosBundleId: 'com.example.lightatech',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBWuKHgkeYifukK0l2Vsf5rRnCsTJ6BMBI',
    appId: '1:930679859953:ios:51840cc93e9b578b019750',
    messagingSenderId: '930679859953',
    projectId: 'light-punch-maker-atech1',
    storageBucket: 'light-punch-maker-atech1.firebasestorage.app',
    iosBundleId: 'com.example.lightatech',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDnX_34M42xFfE6W8dCdMGM3hortg9Ec-Q',
    appId: '1:930679859953:web:8f8b884a8dd8ef93019750',
    messagingSenderId: '930679859953',
    projectId: 'light-punch-maker-atech1',
    authDomain: 'light-punch-maker-atech1.firebaseapp.com',
    storageBucket: 'light-punch-maker-atech1.firebasestorage.app',
    measurementId: 'G-P0ZPD17NQ0',
  );
}
