import 'package:flutter/material.dart';
import 'package:cloud_firestore/cloud_firestore.dart';
import 'package:pdf/pdf.dart';
import 'package:pdf/widgets.dart' as pw;
import 'package:printing/printing.dart';

class QuotationDetailScreen extends StatelessWidget {
  final String quoteId;
  const QuotationDetailScreen({super.key, required this.quoteId});

  String _prettyValue(dynamic value) {
    if (value == null) return "-";
    if (value is bool) return value ? "Yes" : "No";
    if (value is List) return value.isEmpty ? "-" : value.join(", ");
    final str = value.toString().trim();
    return str.isEmpty ? "-" : str;
  }

  // ── CLASS-LEVEL METHOD (not inside build) ────────────────────────────────
  Future<void> _downloadPdf(
      String quoteId,
      Map<String, dynamic> designerData,
      String status,
      ) async {
    const showFields = [
      "PartyName", "particularJobName", "Orderby", "DeliveryAt",
      "Priority", "Remark", "PlyType", "Blade", "Creasing",
      "Perforation", "ZigZagBlade", "RubberType", "HoleType",
      "EmbossStatus", "StrippingType", "RubberFixingDone",
      "WhiteProfileRubber", "DesigningStatus",
    ];

    const labelOverrides = <String, String>{
      "PartyName": "Party Name",
      "particularJobName": "Job Name",
      "Orderby": "Order By",
      "DeliveryAt": "Delivery At",
      "PlyType": "Ply",
      "ZigZagBlade": "Zig Zag Blade",
      "RubberType": "Rubber",
      "HoleType": "Hole",
      "EmbossStatus": "Emboss",
      "StrippingType": "Stripping",
      "RubberFixingDone": "Rubber Fixing Done",
      "WhiteProfileRubber": "White Profile Rubber",
      "DesigningStatus": "Designing Status",
    };

    final rows = <List<String>>[];
    for (final key in showFields) {
      final value = designerData[key];
      if (value == null || value.toString().trim().isEmpty) continue;
      final label = labelOverrides[key] ??
          key.replaceAllMapped(RegExp(r'([A-Z])'), (m) => ' ${m[0]}').trim();
      rows.add([label, value.toString()]);
    }

    final pdf = pw.Document();

    pdf.addPage(
      pw.Page(
        margin: const pw.EdgeInsets.all(32),
        build: (pw.Context context) => pw.Column(
          crossAxisAlignment: pw.CrossAxisAlignment.start,
          children: [
            pw.Row(
              mainAxisAlignment: pw.MainAxisAlignment.spaceBetween,
              children: [
                pw.Text("QUOTATION",
                    style: pw.TextStyle(
                        fontSize: 22, fontWeight: pw.FontWeight.bold)),
                pw.Text(quoteId,
                    style: pw.TextStyle(
                        fontSize: 13, fontWeight: pw.FontWeight.bold)),
              ],
            ),
            pw.SizedBox(height: 4),
            pw.Text("Status: ${status.toUpperCase()}",
                style: const pw.TextStyle(
                    fontSize: 11, color: PdfColors.grey600)),
            pw.SizedBox(height: 16),
            pw.Divider(),
            pw.SizedBox(height: 12),
            pw.Table(
              columnWidths: {
                0: const pw.FlexColumnWidth(4),
                1: const pw.FlexColumnWidth(6),
              },
              children: [
                pw.TableRow(
                  decoration:
                  const pw.BoxDecoration(color: PdfColors.grey200),
                  children: [
                    pw.Padding(
                      padding: const pw.EdgeInsets.all(6),
                      child: pw.Text("Field",
                          style: pw.TextStyle(
                              fontWeight: pw.FontWeight.bold,
                              fontSize: 11)),
                    ),
                    pw.Padding(
                      padding: const pw.EdgeInsets.all(6),
                      child: pw.Text("Value",
                          style: pw.TextStyle(
                              fontWeight: pw.FontWeight.bold,
                              fontSize: 11)),
                    ),
                  ],
                ),
                ...rows.map((row) => pw.TableRow(
                  children: [
                    pw.Padding(
                      padding: const pw.EdgeInsets.symmetric(
                          horizontal: 6, vertical: 5),
                      child: pw.Text(row[0],
                          style: const pw.TextStyle(
                              fontSize: 11,
                              color: PdfColors.grey700)),
                    ),
                    pw.Padding(
                      padding: const pw.EdgeInsets.symmetric(
                          horizontal: 6, vertical: 5),
                      child: pw.Text(row[1],
                          style: const pw.TextStyle(fontSize: 11)),
                    ),
                  ],
                )),
              ],
            ),
            pw.SizedBox(height: 20),
            pw.Divider(),
            pw.SizedBox(height: 6),
            pw.Text("Generated by LPM System",
                style: const pw.TextStyle(
                    fontSize: 9, color: PdfColors.grey500)),
          ],
        ),
      ),
    );

    await Printing.layoutPdf(onLayout: (format) async => pdf.save());
  }

  @override
  Widget build(BuildContext context) {
    const showFields = [
      "PartyName", "particularJobName", "Orderby", "DeliveryAt",
      "Priority", "Remark", "PlyType", "Blade", "Creasing",
      "Perforation", "ZigZagBlade", "RubberType", "HoleType",
      "EmbossStatus", "StrippingType", "RubberFixingDone",
      "WhiteProfileRubber", "DesigningStatus",
    ];

    const labelOverrides = <String, String>{
      "PartyName": "Party Name",
      "particularJobName": "Job Name",
      "Orderby": "Order By",
      "DeliveryAt": "Delivery At",
      "PlyType": "Ply",
      "ZigZagBlade": "Zig Zag Blade",
      "RubberType": "Rubber",
      "HoleType": "Hole",
      "EmbossStatus": "Emboss",
      "StrippingType": "Stripping",
      "RubberFixingDone": "Rubber Fixing Done",
      "WhiteProfileRubber": "White Profile Rubber",
      "DesigningStatus": "Designing Status",
    };

    return Scaffold(
      appBar: AppBar(title: Text(quoteId)),
      body: FutureBuilder<DocumentSnapshot>(
        future: FirebaseFirestore.instance
            .collection("quotations")
            .doc(quoteId)
            .get(),
        builder: (context, snap) {
          if (!snap.hasData) {
            return const Center(child: CircularProgressIndicator());
          }
          if (!snap.data!.exists) {
            return const Center(child: Text("Quotation not found"));
          }

          final data = snap.data!.data() as Map<String, dynamic>;
          final designerData =
          (data["designer"]?["data"] ?? {}) as Map<String, dynamic>;
          final status = (data["status"] ?? "pending").toString();

          return SingleChildScrollView(
            padding: const EdgeInsets.all(16),
            child: Column(
              crossAxisAlignment: CrossAxisAlignment.start,
              children: [
                // ── Header ───────────────────────────────────────────
                Container(
                  padding: const EdgeInsets.all(16),
                  decoration: BoxDecoration(
                    color: Colors.grey.shade100,
                    borderRadius: BorderRadius.circular(14),
                  ),
                  child: Row(
                    mainAxisAlignment: MainAxisAlignment.spaceBetween,
                    children: [
                      const Text("Quotation Details",
                          style: TextStyle(
                              fontSize: 16,
                              fontWeight: FontWeight.w600)),
                      Container(
                        padding: const EdgeInsets.symmetric(
                            horizontal: 12, vertical: 6),
                        decoration: BoxDecoration(
                          color: Colors.amber.shade100,
                          borderRadius: BorderRadius.circular(8),
                        ),
                        child: Text(quoteId),
                      ),
                    ],
                  ),
                ),

                const SizedBox(height: 16),

                // ── Status badge ──────────────────────────────────────
                Container(
                  padding: const EdgeInsets.symmetric(
                      horizontal: 12, vertical: 8),
                  decoration: BoxDecoration(
                    color: const Color(0xFFFFF3E0),
                    borderRadius: BorderRadius.circular(8),
                    border:
                    Border.all(color: const Color(0xFFFFCC80)),
                  ),
                  child: Text(
                    "Status: ${status.toUpperCase()}",
                    style: const TextStyle(
                        fontWeight: FontWeight.w700,
                        color: Color(0xFFE65100)),
                  ),
                ),

                const SizedBox(height: 12),

                // ── Download Button ───────────────────────────────────
                SizedBox(
                  width: double.infinity,
                  child: ElevatedButton.icon(
                    onPressed: () =>
                        _downloadPdf(quoteId, designerData, status),
                    icon: const Icon(Icons.download, color: Colors.black),
                    label: const Text("Download PDF",
                        style: TextStyle(color: Colors.black)),
                    style: ElevatedButton.styleFrom(
                      backgroundColor: const Color(0xFFF8D94B),
                      shape: RoundedRectangleBorder(
                          borderRadius: BorderRadius.circular(8)),
                    ),
                  ),
                ),

                const SizedBox(height: 20),

                // ── Info rows ─────────────────────────────────────────
                const Text(
                  "INFORMATION",
                  style: TextStyle(
                      fontSize: 12,
                      fontWeight: FontWeight.w600,
                      color: Colors.grey,
                      letterSpacing: 1),
                ),
                const SizedBox(height: 12),

                ...showFields.map((key) {
                  final value = designerData[key];
                  if (value == null ||
                      value.toString().trim().isEmpty) {
                    return const SizedBox.shrink();
                  }
                  final label = labelOverrides[key] ??
                      key
                          .replaceAllMapped(RegExp(r'([A-Z])'),
                              (m) => ' ${m[0]}')
                          .trim();

                  return Column(
                    children: [
                      Padding(
                        padding:
                        const EdgeInsets.symmetric(vertical: 10),
                        child: Row(
                          children: [
                            Expanded(
                              flex: 4,
                              child: Text(label,
                                  style: const TextStyle(
                                      color: Colors.grey,
                                      fontSize: 13)),
                            ),
                            Expanded(
                              flex: 6,
                              child: Text(
                                _prettyValue(value),
                                textAlign: TextAlign.right,
                                style: const TextStyle(
                                    fontSize: 13,
                                    color: Colors.black),
                              ),
                            ),
                          ],
                        ),
                      ),
                      Divider(
                          color: Colors.grey.shade300, height: 1),
                    ],
                  );
                }).toList(),
              ],
            ),
          );
        },
      ),
    );
  }
}